# Generated by Django 6.0 on 2025-12-18 22:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('schedules', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='class_room',
            new_name='class_name',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('teacher', 'class_name', 'subject', 'day_of_week', 'start_time')},
        ),
    ]
