name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t django-app .

      - name: Run container test
        run: |
          docker run -d --name test-app django-app
          sleep 10
          docker logs test-app
          docker stop test-app

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Simulated Deploy
        run: echo "Deploy successful 🚀"